import Link from "next/link";
import { ArrowRight, CheckCircle, ChevronRight } from "lucide-react";

const services = [
  {title:"Pre-cast Concrete Walls",subtitle:"Boundary & Security Walls",description:"Our pre-cast wall panels are manufactured in a controlled environment to exact specifications, ensuring consistent quality and strength.",features:["Available in heights from 1.8m to 3.6m","Plain, textured, or decorative finishes","Integrated column and panel system","Rapid installation","SANS 10400 compliant","Optional electric fencing integration"],cta:"Get a Wall Quote"},
  {title:"Concrete Houses",subtitle:"Pre-cast Residential Construction",description:"Modern, energy-efficient homes built with pre-cast concrete panels. Our system reduces build time by up to 60%.",features:["Customisable floor plans","Superior thermal and acoustic insulation","Fire-resistant and durable","Build time: 4-8 weeks","NHBRC registered","Modern architectural finishes"],cta:"Plan Your Home"},
  {title:"Retaining Walls",subtitle:"Engineered Earth Retention",description:"Pre-cast retaining walls designed for soil stabilisation, landscaping, and infrastructure projects.",features:["Gravity, cantilever, and counterfort designs","Heights up to 6m","Interlocking system","Suitable for all soil conditions","Drainage integrated","Cost-effective alternative"],cta:"Request Retaining Wall Quote"},
  {title:"Decorative Concrete",subtitle:"Architectural & Design Finishes",description:"Transform concrete from functional to beautiful with stamped patterns, exposed aggregate, polished finishes, and custom staining.",features:["Stamped concrete patterns","Exposed aggregate","Acid staining and integral colour","Polished concrete floors","Custom form liners","UV-stable sealers"],cta:"Explore Finishes"},
];

export default function ServicesPage() {
  return (<>
    <section className="border-b border-border bg-card"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-16 sm:py-24"><p className="text-sm font-medium tracking-[0.2em] uppercase text-primary mb-2">Our Services</p><h1 className="font-serif text-4xl sm:text-5xl font-bold tracking-tight text-foreground">Pre-cast Concrete<br />Solutions</h1><p className="mt-4 text-lg text-muted-foreground max-w-2xl">From boundary walls to complete homes, we deliver quality pre-cast concrete products engineered for South African conditions.</p></div></section>
    <section className="py-16 sm:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="space-y-16">{services.map((service,i) => (<div key={i} className="grid lg:grid-cols-2 gap-10 lg:gap-16 items-start"><div><p className="text-xs font-bold tracking-[0.2em] uppercase text-cta mb-2">{service.subtitle}</p><h2 className="font-serif text-3xl sm:text-4xl font-bold tracking-tight text-foreground mb-4">{service.title}</h2><p className="text-muted-foreground leading-relaxed mb-6">{service.description}</p><ul className="space-y-3 mb-8">{service.features.map((f,j)=>(<li key={j} className="flex items-start gap-3"><CheckCircle className="h-5 w-5 shrink-0 text-primary mt-0.5" /><span className="text-sm text-foreground/80">{f}</span></li>))}</ul><Link href="/quote" className="inline-flex items-center gap-2 rounded-sm bg-cta px-6 py-3 text-sm font-bold text-cta-foreground transition-all hover:bg-cta/90">{service.cta}<ArrowRight className="h-4 w-4" /></Link></div><div className="rounded-sm border border-border bg-muted/50 aspect-[4/3] flex items-center justify-center"><div className="text-center p-8"><div className="inline-flex h-16 w-16 items-center justify-center rounded-sm bg-primary/10 mb-4"><svg viewBox="0 0 24 24" className="h-8 w-8 text-primary" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="3" width="18" height="18" rx="2"/><line x1="3" y1="9" x2="21" y2="9"/><line x1="9" y1="21" x2="9" y2="9"/></svg></div><p className="font-serif text-lg font-bold text-foreground">{service.title}</p><p className="text-xs text-muted-foreground mt-1">Project images coming soon</p></div></div></div>))}</div></div></section>
    <section className="bg-card border-t border-border py-16 sm:py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 text-center"><h2 className="font-serif text-3xl font-bold text-foreground">Not Sure What You Need?</h2><p className="mt-3 text-muted-foreground max-w-lg mx-auto">Our team can assess your site and recommend the best solution.</p><Link href="/contact" className="mt-6 inline-flex items-center gap-2 rounded-sm bg-primary px-6 py-3 text-sm font-bold text-primary-foreground transition-all hover:bg-primary/90">Contact Us<ChevronRight className="h-4 w-4" /></Link></div></section>
  </>);
}
