"use client";
import { useState } from "react";
import { Send, ChevronLeft, ChevronRight, CheckCircle } from "lucide-react";

export default function QuotePage() {
  const [currentStep, setCurrentStep] = useState(0);
  const [submitted, setSubmitted] = useState(false);
  const [formData, setFormData] = useState({service:"",dimensions:"",terrain:"",timeline:"",name:"",email:"",phone:"",location:""});
  const updateField = (f:string,v:string) => setFormData(p=>({...p,[f]:v}));
  const canProceed = () => {if(currentStep===0)return formData.service!=="";if(currentStep===1)return formData.dimensions!==""&&formData.terrain!=="";if(currentStep===2)return formData.name!==""&&formData.email!==""&&formData.phone!=="";return true};
  
  if(submitted) return (<section className="py-16 sm:py-24"><div className="mx-auto max-w-2xl px-4 text-center py-12"><div className="inline-flex h-16 w-16 items-center justify-center rounded-sm bg-primary/10 mb-6"><CheckCircle className="h-8 w-8 text-primary" /></div><h2 className="font-serif text-3xl font-bold text-foreground mb-3">Quote Request Sent!</h2><p className="text-muted-foreground">Thank you! Our team will review and get back to you within 48 hours.</p><p className="mt-4 text-sm text-muted-foreground">For urgent enquiries: <a href="tel:+27123456789" className="text-primary hover:underline font-bold">+27 12 345 6789</a></p></div></section>);
  
  const steps = [{label:"Service"},{label:"Details"},{label:"Contact"}];
  const services = [{value:"walls",label:"Pre-cast Walls"},{value:"house",label:"Concrete House"},{value:"retaining",label:"Retaining Wall"},{value:"decorative",label:"Decorative Concrete"},{value:"other",label:"Other"}];
  const terrains = [{value:"flat",label:"Flat / Level"},{value:"sloped",label:"Sloped"},{value:"rocky",label:"Rocky"},{value:"unsure",label:"Not Sure"}];
  const timelines = [{value:"urgent",label:"ASAP (2 weeks)"},{value:"month",label:"Within 1 month"},{value:"quarter",label:"Within 3 months"},{value:"planning",label:"Just planning"}];

  return (<>
    <section className="border-b border-border bg-card"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-16 sm:py-24"><p className="text-sm font-medium tracking-[0.2em] uppercase text-primary mb-2">Get Started</p><h1 className="font-serif text-4xl sm:text-5xl font-bold tracking-tight text-foreground">Request a Quote</h1><p className="mt-4 text-lg text-muted-foreground max-w-2xl">Tell us about your project and we'll provide a detailed estimate within 48 hours.</p></div></section>
    <section className="py-16 sm:py-24"><div className="mx-auto max-w-2xl px-4 sm:px-6 lg:px-8">
      <div className="flex items-center justify-center gap-2 mb-12">{steps.map((s,i)=>(<div key={i} className="flex items-center gap-2"><div className={"flex h-8 w-8 items-center justify-center rounded-sm text-xs font-bold "+(i<currentStep?"bg-primary text-primary-foreground":i===currentStep?"bg-cta text-cta-foreground":"bg-muted text-muted-foreground")}>{i<currentStep?<CheckCircle className="h-4 w-4" />:i+1}</div><span className="text-xs font-medium hidden sm:inline">{s.label}</span>{i<steps.length-1&&<div className={"w-12 sm:w-16 h-0.5 "+(i<currentStep?"bg-primary":"bg-border")} />}</div>))}</div>
      <form onSubmit={e=>{e.preventDefault();setSubmitted(true)}}>
        <div className="rounded-sm border border-border bg-card p-6 sm:p-8">
          {currentStep===0&&<div className="space-y-6"><h2 className="font-serif text-xl font-bold">What service do you need?</h2><div className="grid gap-3">{services.map(o=>(<label key={o.value} className={"flex items-center gap-4 rounded-sm border px-4 py-3.5 cursor-pointer "+(formData.service===o.value?"border-primary bg-primary/5":"border-border hover:border-primary/30")}><input type="radio" name="service" checked={formData.service===o.value} onChange={e=>updateField("service",e.target.value)} className="h-4 w-4 accent-primary" /><span className="text-sm font-medium">{o.label}</span></label>))}</div></div>}
          {currentStep===1&&<div className="space-y-6"><h2 className="font-serif text-xl font-bold">Project details</h2><div><label className="block text-sm font-bold mb-1.5">Approximate dimensions</label><input type="text" value={formData.dimensions} onChange={e=>updateField("dimensions",e.target.value)} placeholder="e.g. 50m x 2.4m wall" className="w-full rounded-sm border border-input bg-background px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-ring" /></div><div><label className="block text-sm font-bold mb-1.5">Terrain type</label><div className="grid grid-cols-2 gap-2">{terrains.map(o=>(<label key={o.value} className={"flex items-center gap-3 rounded-sm border px-3 py-2.5 cursor-pointer "+(formData.terrain===o.value?"border-primary bg-primary/5":"border-border hover:border-primary/30")}><input type="radio" name="terrain" checked={formData.terrain===o.value} onChange={e=>updateField("terrain",e.target.value)} className="h-3.5 w-3.5 accent-primary" /><span className="text-xs font-medium">{o.label}</span></label>))}</div></div><div><label className="block text-sm font-bold mb-1.5">Timeline</label><div className="space-y-2">{timelines.map(o=>(<label key={o.value} className={"flex items-center gap-3 rounded-sm border px-4 py-2.5 cursor-pointer "+(formData.timeline===o.value?"border-primary bg-primary/5":"border-border hover:border-primary/30")}><input type="radio" name="timeline" checked={formData.timeline===o.value} onChange={e=>updateField("timeline",e.target.value)} className="h-4 w-4 accent-primary" /><span className="text-sm font-medium">{o.label}</span></label>))}</div></div></div>}
          {currentStep===2&&<div className="space-y-5"><h2 className="font-serif text-xl font-bold">Your contact details</h2><div className="grid sm:grid-cols-2 gap-4"><div><label className="block text-sm font-bold mb-1.5">Full Name *</label><input type="text" value={formData.name} onChange={e=>updateField("name",e.target.value)} className="w-full rounded-sm border border-input bg-background px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-ring" placeholder="John Smith" /></div><div><label className="block text-sm font-bold mb-1.5">Email *</label><input type="email" value={formData.email} onChange={e=>updateField("email",e.target.value)} className="w-full rounded-sm border border-input bg-background px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-ring" placeholder="john@example.com" /></div></div><div className="grid sm:grid-cols-2 gap-4"><div><label className="block text-sm font-bold mb-1.5">Phone *</label><input type="tel" value={formData.phone} onChange={e=>updateField("phone",e.target.value)} className="w-full rounded-sm border border-input bg-background px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-ring" placeholder="+27 12 345 6789" /></div><div><label className="block text-sm font-bold mb-1.5">Location</label><input type="text" value={formData.location} onChange={e=>updateField("location",e.target.value)} className="w-full rounded-sm border border-input bg-background px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-ring" placeholder="e.g. Silver Lakes, Pretoria" /></div></div></div>}
        </div>
        <div className="flex items-center justify-between mt-6">
          {currentStep>0?<button type="button" onClick={()=>setCurrentStep(currentStep-1)} className="inline-flex items-center gap-1.5 rounded-sm border border-border px-4 py-2.5 text-sm font-medium hover:border-primary hover:text-primary"><ChevronLeft className="h-4 w-4" />Back</button>:<div />}
          {currentStep<2?<button type="button" disabled={!canProceed()} onClick={()=>setCurrentStep(currentStep+1)} className="inline-flex items-center gap-1.5 rounded-sm bg-primary px-5 py-2.5 text-sm font-bold text-primary-foreground disabled:opacity-40">Next<ChevronRight className="h-4 w-4" /></button>:<button type="submit" disabled={!canProceed()} className="inline-flex items-center gap-2 rounded-sm bg-cta px-6 py-3 text-sm font-bold text-cta-foreground disabled:opacity-40"><Send className="h-4 w-4" />Submit Quote Request</button>}
        </div>
      </form>
    </div></section>
  </>);
}
