import Link from "next/link";
import { Shield, Users, Target, Heart, ArrowRight } from "lucide-react";

export default function AboutPage() {
  return (<>
    <section className="border-b border-border bg-card"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-16 sm:py-24"><p className="text-sm font-medium tracking-[0.2em] uppercase text-primary mb-2">About Us</p><h1 className="font-serif text-4xl sm:text-5xl font-bold tracking-tight text-foreground">Built on Trust,<br />Grounded in Quality</h1><p className="mt-4 text-lg text-muted-foreground max-w-2xl">Rietvlei Concrete has been serving Gauteng with premium pre-cast concrete solutions for over 15 years.</p></div></section>
    <section className="py-16 sm:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid lg:grid-cols-2 gap-12 lg:gap-20 items-center"><div><h2 className="font-serif text-3xl sm:text-4xl font-bold tracking-tight text-foreground mb-6">Our Story</h2><div className="space-y-4 text-muted-foreground leading-relaxed"><p>Rietvlei Concrete was founded with a simple belief: that concrete construction could be faster, more affordable, and higher quality through pre-cast manufacturing.</p><p>Starting with a small casting yard in Rietvlei, we invested in precision moulds, quality control systems, and skilled craftsmanship. Word spread quickly.</p><p>Today, we're proud to have completed over 200 projects across Gauteng. Every project carries the same commitment to excellence.</p></div></div><div className="space-y-5">{[{icon:Shield,title:"Quality Without Compromise",desc:"Every panel is manufactured to SANS standards. We test, inspect, and certify."},{icon:Users,title:"Skilled Craftsmanship",desc:"Our team brings decades of combined experience."},{icon:Target,title:"On Time, On Budget",desc:"Pre-cast means predictable. We commit to timelines and deliver."},{icon:Heart,title:"Customer First",desc:"We listen, advise honestly, and build what you actually need."}].map((v,i)=>(<div key={i} className="flex gap-4 rounded-sm border border-border bg-card p-5"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-sm bg-primary/10"><v.icon className="h-5 w-5 text-primary" /></div><div><h3 className="font-serif text-base font-bold text-foreground">{v.title}</h3><p className="text-sm text-muted-foreground leading-relaxed mt-1">{v.desc}</p></div></div>))}</div></div></div></section>
    <section className="bg-card border-y border-border py-16 sm:py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="text-center mb-10"><h2 className="font-serif text-3xl font-bold text-foreground">Our Service Area</h2><p className="mt-2 text-muted-foreground max-w-lg mx-auto">Based in Rietvlei, we serve the greater Gauteng region within a 50km radius.</p></div><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-3">{["Pretoria","Centurion","Midrand","Bronkhorstspruit","Cullinan","Rayton","Silver Lakes","Mooikloof","Zambezi","Montana","Wonderboom","Equestria"].map(a=>(<div key={a} className="rounded-sm border border-border bg-muted/30 px-3 py-2.5 text-center text-sm font-medium text-foreground/80">{a}</div>))}</div></div></section>
    <section className="py-16 sm:py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 text-center"><h2 className="font-serif text-3xl font-bold text-foreground">Let's Build Something Great</h2><p className="mt-3 text-muted-foreground max-w-lg mx-auto">Whether it's a boundary wall or your dream home, we're ready.</p><div className="mt-6 flex flex-col sm:flex-row gap-4 justify-center"><Link href="/quote" className="inline-flex items-center gap-2 rounded-sm bg-cta px-6 py-3 text-sm font-bold text-cta-foreground transition-all hover:bg-cta/90">Get a Quote<ArrowRight className="h-4 w-4" /></Link><Link href="/contact" className="inline-flex items-center gap-2 rounded-sm border-2 border-border px-6 py-3 text-sm font-bold text-foreground transition-all hover:border-primary hover:text-primary">Contact Us</Link></div></div></section>
  </>);
}
